### PR TITLE
Review

### PR DESCRIPTION
**Pull request by viper-admin**
>  **Pull request** :twisted_rightwards_arrows: created by bitbucket user **RKor** on 2015-05-19 17:56
> Last updated on 2020-02-14 14:40
> Original Bitbucket pull request id: 14
>
> Participants:
>
> * **@mschwerhoff** (reviewer)
> * bitbucket user **wuestholz** (reviewer)
> * bitbucket user **RKor**
>
> Source: https://github.com/viperproject/silicon/commit/3aed15b1ec3d20e7eac87996befbde29f2ebff67 on branch `viperproject/silicon-verifiedif/default`
> Destination: https://github.com/viperproject/silicon/commit/76f21ec30b0fe9e7be00e4e6f56db9fd42984a42 on branch `master`
>
> State: **`OPEN`**

Not intended to be actuallly pulled, just for feedback purposes.

### CODE REVIEW

**Comment by viper-admin** [comment]
> Bitbucket user **wuestholz** commented on 2015-05-21 07:58
>
> **Outdated location:** line 289 of `src/main/scala/decider/Decider.scala`

Minor: I would not match on a boolean expression. That's what conditionals are for.

**Comment by viper-admin** [comment]
> Bitbucket user **wuestholz** commented on 2015-05-21 08:28
>
> **Outdated location:** line 39 of `src/main/scala/Consumer.scala`

Maybe 'currentVI' would be better.

**Comment by viper-admin** [comment]
> Bitbucket user **wuestholz** commented on 2015-05-21 08:30
>
> **Outdated location:** line 51 of `src/main/scala/Consumer.scala`

Declaring a local variable with the same name doesn't seem like such a great idea. Actually, it seems like 'lastVI' would make sense for the local variable.

**Comment by viper-admin** [comment]
> Bitbucket user **wuestholz** commented on 2015-05-21 08:31
>
> **Outdated location:** line 68 of `src/main/scala/Consumer.scala`

See above (name shadowing).

**Comment by viper-admin** [comment]
> Bitbucket user **wuestholz** commented on 2015-05-21 08:31
>
> **Outdated location:** line 52 of `src/main/scala/Executor.scala`

Needed?

**Comment by viper-admin** [comment]
> Bitbucket user **wuestholz** commented on 2015-05-21 08:33
>
> **Outdated location:** line 288 of `src/main/scala/Executor.scala`

It seems like the smoke check *should* trigger for 'assert false verified-if(false)'.

**Comment by viper-admin** [comment]
> Bitbucket user **RKor** commented on 2015-05-21 09:00
>
> **Location:** `src/main/scala/Executor.scala`

> Needed?

Not anymore will delete.

**Comment by mschwerhoff** [comment]
Outdated

**Pull request closed without merging**
